# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(max_length=250)),
                ('book_title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('book_title', models.CharField(max_length=250)),
                ('Book_Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.Book_Series')),
            ],
        ),
    ]
